### ISSUE TITLE
[PE-D] reminders CCA displayed incorrectly after re-opening app containing CCA.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-2/tp#165]
After re-opening app with existing CCAs, and snoozed reminders, new reminders do not show CCA label, as shown below. Might be an internal display state issue.

![reopen_fail.png](https://raw.githubusercontent.com/juliussneezer04/ped/main/files/2edfa98e-b7ed-4369-99b5-243e95848d70.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: juliussneezer04/ped#10

**Comment by okyntary** [comment]
This is an issue in the v1.3 release: the v1.3.1 `.jar` file can replicate this issue. However, the latest master branch does not have this issue, so there's nothing for me to fix.

I'm guessing that this is because the v1.3.1 `.jar` file was not created with the very latest version of my storage changes.
